### ISSUE TITLE
Unable to work in webgl.

### ISSUE THREAD

**Issue by kris-w-dev** [ColinLeung-NiloCat/UnityURP-MobileDrawMeshInstancedIndirectExample#4]
<img width="960" alt="733baab063d7cec5e6f1dd256b9566a" src="https://github.com/ColinLeung-NiloCat/UnityURP-MobileDrawMeshInstancedIndirectExample/assets/704748/ae1d013b-97fa-4635-bf64-6b2153f0d723">

Unable to render grass in browser

**Comment by JijaProGamer** [comment]
This is because webgl doesnt support compute shaders

**Comment by ColinLeung-NiloCat** [comment]
webgl doesnt support compute shaders
