### ISSUE TITLE
Pink triangle when built in Unity 2022.3.6

### ISSUE THREAD

**Issue by Torgo13** [ColinLeung-NiloCat/UnityURP-MobileDrawMeshInstancedIndirectExample#5]
In Unity 2022.3.5 and 2022.3.6 the grass renders in the editor, but in a built application only a single pink triangle is drawn. If you move the camera close to the triangle the framerate drops significantly. The triangle can only be seen from one side.

Editor:
![2023-08-05](https://github.com/ColinLeung-NiloCat/UnityURP-MobileDrawMeshInstancedIndirectExample/assets/24195653/3510c117-f878-4095-86ac-72ce5de1462c)

Standalone build:
![2023-08-05 (1)](https://github.com/ColinLeung-NiloCat/UnityURP-MobileDrawMeshInstancedIndirectExample/assets/24195653/75c3f783-037d-4f35-b9ee-a41e6b119f66)

The same issues occurs on:
- Windows Direct 11
- Windows Vulkan
- Android Vulkan
- iOS Metal

Note: Dynamic Resolution is broken in Unity 2022 so disable it on the camera before testing.

In the documentation for [Graphics.DrawMeshInstancedIndirect](https://docs.unity3d.com/ScriptReference/Graphics.DrawMeshInstancedIndirect.html), it says:
This function is now obsolete. Use [Graphics.RenderMeshIndirect](https://docs.unity3d.com/ScriptReference/Graphics.RenderMeshIndirect.html) instead. Draws the same mesh multiple times using GPU instancing.

However, I was able to get the sample code in [Graphics.DrawMeshInstancedIndirect](https://docs.unity3d.com/ScriptReference/Graphics.DrawMeshInstancedIndirect.html) to render a mesh such as a plane or cube in both the editor and a built application. The mesh wasn't pink like the grass, but they were rendered in the same position so it appeared like a single object. The example script is supposed to assign random positions to each instance but this doesn't seem to be working.

**Comment by woojehyun** [comment]
Try changing the tag to "RenderPipeline" = "UniversalRenderPipeline" -> "RenderPipeline" = "UniversalPipeline".

**Comment by Torgo13** [comment]
Thank you @woojehyun!
