### ISSUE TITLE
Licence 

### ISSUE THREAD

**Issue by viktorbrenek** [ColinLeung-NiloCat/UnityURP-MobileDrawMeshInstancedIndirectExample#6]
Hello friend, 
i am terribly sorry to create an issue. But I have no idea how to send you a message :/
Please can I ask, if this grass project can be used in my RPG game? I really like the performance and stylized look. 
I can see the licence is MIT. But i just want to be sure. 
Thank you very much for any answer, and once again I am sorry to contact you this way. 

I will delete the message if needed. 

Have a nice day!! :))

**Comment by ColinLeung-NiloCat** [comment]
you can do whatever you want with the code
